name: udacity_fastapi_project
channels:
  - defaults
dependencies:
  - pip=24.0
  - python=3.12.4
  - pip:
    - black==24.4.2
    - dvc==3.51.2
    - dvc-gdrive==3.0.1
    - fastapi==0.111.0
    - flake8==7.1.0
    - Flask==0.12.2
    - gunicorn==22.0.0
    - ipdb==0.13.13
    - ipython==8.25.0
    - jedi==0.18.1
    - jupyter_core==5.5.0
    - nbdime==4.0.1
    - notebook==7.0.8
    - numpy==2.0.0
    - pandas==2.2.2
    - pylint==3.2.3
    - pytest==8.2.2
    - requests==2.32.3
    - scikit-learn==1.5.0
    - scipy==1.13.1
    - uvicorn[standard]==0.30.1
