stages:
  preprocessing:
    cmd: python preprocessing.py
    deps:
    - data/census.csv
    - preprocessing.py
    outs:
    - data/clean_census.gz
  train:
    cmd: python train.py
    deps:
    - data/clean_census.gz
    - train.py
    params:
    - parameters.yaml:
      - model.parameters.C
      - model.parameters.penalty
    outs:
    - model/logistic_regression.pkl
    metrics:
    - model/score.json:
        cache: false
