stages:
  preprocessing:
    cmd: python preprocessing.py
    deps:
    - data/census.csv
    - preprocessing.py
    outs:
    - data/clean_census.gz
  feature_engineering:
    cmd: python feature_engineering.py
    deps:
    - data/clean_census.gz
    - feature_engineering.py
    outs:
    - data/eng_census.gz
