stages:
  preprocessing:
    cmd: python starter/ml/data.py
    deps:
    - data/census.csv
    - starter/ml/data.py
    outs:
    - data/clean_census.gz
  train_model:
    cmd: python starter/train_model.py
    deps:
    - data/clean_census.gz
    - starter/train_model.py
    params:
    - parameters.yaml:
      - model.parameters.C
      - model.parameters.penalty
    outs:
    - model/logistic_regression.pkl
    metrics:
    - model/score.json:
        cache: false
    - model/strata_score.json:
        cache: false
