columns:
  # education was dropped since it contains no independant information relative to education-num
  categorical:
    - workclass
    - marital-status
    - occupation
    - relationship
    - race
    - sex
    - native-country
  numerical:
    - age
    - education-num
    - capital-gain
    - capital-loss
    - hours-per-week
  strata:
    - workclass
    - race
    - sex
model:
  parameters:
    C: 1.0
    penalty: l2
